# Generated by Django 3.0.5 on 2020-05-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('FatherName', models.CharField(max_length=30)),
                ('MotherName', models.CharField(max_length=30)),
                ('DOB', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
                ('MobileNo', models.IntegerField()),
                ('SSCMarks', models.IntegerField()),
                ('NameOfTheSchool', models.CharField(max_length=30)),
                ('InterMarks', models.IntegerField()),
                ('NameOfTheCollege', models.CharField(max_length=30)),
                ('State', models.CharField(max_length=30)),
                ('Dist', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=30)),
                ('Pincode', models.IntegerField()),
                ('Address1', models.CharField(default='blg', max_length=30)),
            ],
        ),
    ]
