# Generated by Django 3.0.5 on 2020-07-02 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appform',
            name='Address1',
        ),
    ]
